//
// AIAnnotation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AIAnnotation: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var image: AIImageReference
    public var category: AICategoryMiniReference
    public var assetDisplayName: String
    public var transforms: String
    public var relativeLeft: Double
    public var relativeTop: Double
    public var relativeWidth: Double
    public var relativeHeight: Double
    public var track: UUID?
    public var createdAt: Date
    public var createdBy: Int?

    public init(id: UUID, image: AIImageReference, category: AICategoryMiniReference, assetDisplayName: String, transforms: String, relativeLeft: Double, relativeTop: Double, relativeWidth: Double, relativeHeight: Double, track: UUID? = nil, createdAt: Date, createdBy: Int? = nil) {
        self.id = id
        self.image = image
        self.category = category
        self.assetDisplayName = assetDisplayName
        self.transforms = transforms
        self.relativeLeft = relativeLeft
        self.relativeTop = relativeTop
        self.relativeWidth = relativeWidth
        self.relativeHeight = relativeHeight
        self.track = track
        self.createdAt = createdAt
        self.createdBy = createdBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case image
        case category
        case assetDisplayName = "asset_display_name"
        case transforms
        case relativeLeft = "relative_left"
        case relativeTop = "relative_top"
        case relativeWidth = "relative_width"
        case relativeHeight = "relative_height"
        case track
        case createdAt = "created_at"
        case createdBy = "created_by"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(image, forKey: .image)
        try container.encode(category, forKey: .category)
        try container.encode(assetDisplayName, forKey: .assetDisplayName)
        try container.encode(transforms, forKey: .transforms)
        try container.encode(relativeLeft, forKey: .relativeLeft)
        try container.encode(relativeTop, forKey: .relativeTop)
        try container.encode(relativeWidth, forKey: .relativeWidth)
        try container.encode(relativeHeight, forKey: .relativeHeight)
        try container.encodeIfPresent(track, forKey: .track)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
    }
}

