//
// AIDatasetExportResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AIDatasetExportResponse: Codable, JSONEncodable, Hashable {

    public var task: TaskInfo

    public init(task: TaskInfo) {
        self.task = task
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case task
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(task, forKey: .task)
    }
}

