//
// AllMediaFilesForBundlesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AllMediaFilesForBundlesRequest: Codable, Hashable {

    public var bundles: Set<Int>

    public init(bundles: Set<Int>) {
        self.bundles = bundles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bundles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bundles, forKey: .bundles)
    }
}

