//
// ArgumentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ArgumentType: Codable, Hashable {

    public var displayName: String?
    public var documentation: [TypeDocumentation]?

    public init(displayName: String? = nil, documentation: [TypeDocumentation]? = nil) {
        self.displayName = displayName
        self.documentation = documentation
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName = "display_name"
        case documentation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(documentation, forKey: .documentation)
    }



}
