//
// AssetCloudLink.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct AssetCloudLink: Codable, Hashable {

    public var id: Int?
    public var connection: CloudConnection?
    public var presignedAssetUrl: String?
    public var createdAt: Date?
    public var asset: Int

    public init(id: Int? = nil, connection: CloudConnection? = nil, presignedAssetUrl: String? = nil, createdAt: Date? = nil, asset: Int) {
        self.id = id
        self.connection = connection
        self.presignedAssetUrl = presignedAssetUrl
        self.createdAt = createdAt
        self.asset = asset
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case connection
        case presignedAssetUrl = "presigned_asset_url"
        case createdAt = "created_at"
        case asset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(connection, forKey: .connection)
        try container.encodeIfPresent(presignedAssetUrl, forKey: .presignedAssetUrl)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encode(asset, forKey: .asset)
    }



}
