//
// AssetBackup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct AssetBackup: Codable, Hashable {

    public var id: Int?
    public var tapeFile: TapeFile?
    public var asset: Asset?
    public var searchHighlight: String?
    public var customFieldsSnapshot: String?

    public init(id: Int? = nil, tapeFile: TapeFile? = nil, asset: Asset? = nil, searchHighlight: String? = nil, customFieldsSnapshot: String? = nil) {
        self.id = id
        self.tapeFile = tapeFile
        self.asset = asset
        self.searchHighlight = searchHighlight
        self.customFieldsSnapshot = customFieldsSnapshot
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tapeFile = "tape_file"
        case asset
        case searchHighlight = "search_highlight"
        case customFieldsSnapshot = "custom_fields_snapshot"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(tapeFile, forKey: .tapeFile)
        try container.encodeIfPresent(asset, forKey: .asset)
        try container.encodeIfPresent(searchHighlight, forKey: .searchHighlight)
        try container.encodeIfPresent(customFieldsSnapshot, forKey: .customFieldsSnapshot)
    }



}
