//
// AssetProjectLink.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssetProjectLink: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var project: Asset
    public var sequenceName: String
    public var asset: Int

    public init(id: Int, project: Asset, sequenceName: String, asset: Int) {
        self.id = id
        self.project = project
        self.sequenceName = sequenceName
        self.asset = asset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case project
        case sequenceName = "sequence_name"
        case asset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(project, forKey: .project)
        try container.encode(sequenceName, forKey: .sequenceName)
        try container.encode(asset, forKey: .asset)
    }
}

