//
// AuthLoginEndpointResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthLoginEndpointResponse: Codable, JSONEncodable, Hashable {

    public var reason: String?
    public var detail: String?
    public var redirect: String?
    public var user: ElementsUserDetail

    public init(reason: String? = nil, detail: String? = nil, redirect: String? = nil, user: ElementsUserDetail) {
        self.reason = reason
        self.detail = detail
        self.redirect = redirect
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
        case detail
        case redirect
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(redirect, forKey: .redirect)
        try container.encode(user, forKey: .user)
    }
}

