//
// Backend.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Backend: Codable, JSONEncodable, Hashable {

    public var name: String
    public var properties: BackendProperties

    public init(name: String, properties: BackendProperties) {
        self.name = name
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(properties, forKey: .properties)
    }
}

