//
// BasicFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct BasicFile: Codable, Hashable {

    public var path: String?
    public var name: String
    public var size: Int?
    public var totalSize: Int?
    public var isDir: Bool?
    public var files: [AnyCodable]?

    public init(path: String? = nil, name: String, size: Int? = nil, totalSize: Int? = nil, isDir: Bool? = nil, files: [AnyCodable]? = nil) {
        self.path = path
        self.name = name
        self.size = size
        self.totalSize = totalSize
        self.isDir = isDir
        self.files = files
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case name
        case size
        case totalSize = "total_size"
        case isDir = "is_dir"
        case files
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(totalSize, forKey: .totalSize)
        try container.encodeIfPresent(isDir, forKey: .isDir)
        try container.encodeIfPresent(files, forKey: .files)
    }



}
