//
// CertificateUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CertificateUpdate: Codable, JSONEncodable, Hashable {

    public var certificate: String
    public var key: String?

    public init(certificate: String, key: String? = nil) {
        self.certificate = certificate
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case certificate
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(certificate, forKey: .certificate)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

