//
// ClickGallery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ClickGallery: Codable, Hashable {

    public var id: Int
    public var name: String
    public var description: String?
    public var presignedLoginUrl: String?

    public init(id: Int, name: String, description: String? = nil, presignedLoginUrl: String? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.presignedLoginUrl = presignedLoginUrl
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case presignedLoginUrl = "presigned_login_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(presignedLoginUrl, forKey: .presignedLoginUrl)
    }



}
