//
// ClientSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientSession: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var user: ElementsUserMini
    public var mountedWorkspaces: String
    public var started: Date
    public var lastUpdated: Date
    public var workstation: WorkstationMini

    public init(id: Int, user: ElementsUserMini, mountedWorkspaces: String, started: Date, lastUpdated: Date, workstation: WorkstationMini) {
        self.id = id
        self.user = user
        self.mountedWorkspaces = mountedWorkspaces
        self.started = started
        self.lastUpdated = lastUpdated
        self.workstation = workstation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case mountedWorkspaces = "mounted_workspaces"
        case started
        case lastUpdated = "last_updated"
        case workstation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(user, forKey: .user)
        try container.encode(mountedWorkspaces, forKey: .mountedWorkspaces)
        try container.encode(started, forKey: .started)
        try container.encode(lastUpdated, forKey: .lastUpdated)
        try container.encode(workstation, forKey: .workstation)
    }
}

