//
// CloudAccountMiniPartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CloudAccountMiniPartialUpdate: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case azure = "azure"
        case aws = "aws"
        case gcloud = "gcloud"
    }
    public var provider: Provider?
    public var name: String?

    public init(provider: Provider? = nil, name: String? = nil) {
        self.provider = provider
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

