//
// DownloadArchive.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct DownloadArchive: Codable, Hashable {

    public enum ProgressUnit: Int, Codable, CaseIterable {
        case _0 = 0
        case _1 = 1
    }
    public var id: UUID?
    public var taskInfo: TaskInfo
    public var uncompressedSize: Int?
    public var size: Int?
    public var expires: String?
    public var files: [String]?
    public var name: String
    public var path: String
    public var createdAt: Date?
    public var progressUnit: ProgressUnit?
    public var user: Int?

    public init(id: UUID? = nil, taskInfo: TaskInfo, uncompressedSize: Int? = nil, size: Int? = nil, expires: String? = nil, files: [String]? = nil, name: String, path: String, createdAt: Date? = nil, progressUnit: ProgressUnit? = nil, user: Int? = nil) {
        self.id = id
        self.taskInfo = taskInfo
        self.uncompressedSize = uncompressedSize
        self.size = size
        self.expires = expires
        self.files = files
        self.name = name
        self.path = path
        self.createdAt = createdAt
        self.progressUnit = progressUnit
        self.user = user
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case taskInfo = "task_info"
        case uncompressedSize = "uncompressed_size"
        case size
        case expires
        case files
        case name
        case path
        case createdAt = "created_at"
        case progressUnit = "progress_unit"
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(taskInfo, forKey: .taskInfo)
        try container.encodeIfPresent(uncompressedSize, forKey: .uncompressedSize)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(expires, forKey: .expires)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encode(name, forKey: .name)
        try container.encode(path, forKey: .path)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(progressUnit, forKey: .progressUnit)
        try container.encodeIfPresent(user, forKey: .user)
    }



}
