//
// ElementsGroupDetailPartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ElementsGroupDetailPartialUpdate: Codable, JSONEncodable, Hashable {

    public var permissions: [String]?
    public var members: [ElementsUserReference]?
    public var ldap: AnyOfLDAPServerReferenceAnyType?
    public var name: String?
    public var ldapDn: String?
    public var unixGroupname: String?
    public var gid: Int?

    public init(permissions: [String]? = nil, members: [ElementsUserReference]? = nil, ldap: AnyOfLDAPServerReferenceAnyType? = nil, name: String? = nil, ldapDn: String? = nil, unixGroupname: String? = nil, gid: Int? = nil) {
        self.permissions = permissions
        self.members = members
        self.ldap = ldap
        self.name = name
        self.ldapDn = ldapDn
        self.unixGroupname = unixGroupname
        self.gid = gid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case permissions
        case members
        case ldap
        case name
        case ldapDn = "ldap_dn"
        case unixGroupname = "unix_groupname"
        case gid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(permissions, forKey: .permissions)
        try container.encodeIfPresent(members, forKey: .members)
        try container.encodeIfPresent(ldap, forKey: .ldap)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(ldapDn, forKey: .ldapDn)
        try container.encodeIfPresent(unixGroupname, forKey: .unixGroupname)
        try container.encodeIfPresent(gid, forKey: .gid)
    }
}

