//
// ElementsUserDetailUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ElementsUserDetailUpdate: Codable, JSONEncodable, Hashable {

    public enum Language: String, Codable, CaseIterable {
        case en = "en"
        case fr = "fr"
        case de = "de"
        case ru = "ru"
    }
    public var allowChangingPassword: Bool?
    public var allowWanLogin: Bool?
    public var avatar: String?
    public var defaultPage: String?
    public var email: String?
    public var expiry: Date?
    public var fmBookmarks: [String]?
    public var fullName: String?
    public var gid: Int?
    public var home: Int?
    public var isExternal: Bool?
    public var isCloud: Bool?
    public var isCloudDefault: Bool?
    public var isEnabled: Bool?
    public var language: Language?
    public var lastSeen: Date?
    public var ldap: AnyOfLDAPServerReferenceAnyType?
    public var ldapDn: String?
    public var passwordChangeRequired: Bool?
    public var permissions: [String]
    public var shaperCeiling: Int?
    public var shaperRate: Int?
    public var totpEnabled: Bool?
    public var uid: Int?
    public var unixUsername: String?
    public var username: String
    public var groups: [Int]

    public init(allowChangingPassword: Bool? = nil, allowWanLogin: Bool? = nil, avatar: String? = nil, defaultPage: String? = nil, email: String? = nil, expiry: Date? = nil, fmBookmarks: [String]? = nil, fullName: String? = nil, gid: Int? = nil, home: Int? = nil, isExternal: Bool? = nil, isCloud: Bool? = nil, isCloudDefault: Bool? = nil, isEnabled: Bool? = nil, language: Language? = nil, lastSeen: Date? = nil, ldap: AnyOfLDAPServerReferenceAnyType? = nil, ldapDn: String? = nil, passwordChangeRequired: Bool? = nil, permissions: [String], shaperCeiling: Int?, shaperRate: Int?, totpEnabled: Bool? = nil, uid: Int? = nil, unixUsername: String? = nil, username: String, groups: [Int]) {
        self.allowChangingPassword = allowChangingPassword
        self.allowWanLogin = allowWanLogin
        self.avatar = avatar
        self.defaultPage = defaultPage
        self.email = email
        self.expiry = expiry
        self.fmBookmarks = fmBookmarks
        self.fullName = fullName
        self.gid = gid
        self.home = home
        self.isExternal = isExternal
        self.isCloud = isCloud
        self.isCloudDefault = isCloudDefault
        self.isEnabled = isEnabled
        self.language = language
        self.lastSeen = lastSeen
        self.ldap = ldap
        self.ldapDn = ldapDn
        self.passwordChangeRequired = passwordChangeRequired
        self.permissions = permissions
        self.shaperCeiling = shaperCeiling
        self.shaperRate = shaperRate
        self.totpEnabled = totpEnabled
        self.uid = uid
        self.unixUsername = unixUsername
        self.username = username
        self.groups = groups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowChangingPassword = "allow_changing_password"
        case allowWanLogin = "allow_wan_login"
        case avatar
        case defaultPage = "default_page"
        case email
        case expiry
        case fmBookmarks = "fm_bookmarks"
        case fullName = "full_name"
        case gid
        case home
        case isExternal = "is_external"
        case isCloud = "is_cloud"
        case isCloudDefault = "is_cloud_default"
        case isEnabled = "is_enabled"
        case language
        case lastSeen = "last_seen"
        case ldap
        case ldapDn = "ldap_dn"
        case passwordChangeRequired = "password_change_required"
        case permissions
        case shaperCeiling = "shaper_ceiling"
        case shaperRate = "shaper_rate"
        case totpEnabled = "totp_enabled"
        case uid
        case unixUsername = "unix_username"
        case username
        case groups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allowChangingPassword, forKey: .allowChangingPassword)
        try container.encodeIfPresent(allowWanLogin, forKey: .allowWanLogin)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(defaultPage, forKey: .defaultPage)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(expiry, forKey: .expiry)
        try container.encodeIfPresent(fmBookmarks, forKey: .fmBookmarks)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(gid, forKey: .gid)
        try container.encodeIfPresent(home, forKey: .home)
        try container.encodeIfPresent(isExternal, forKey: .isExternal)
        try container.encodeIfPresent(isCloud, forKey: .isCloud)
        try container.encodeIfPresent(isCloudDefault, forKey: .isCloudDefault)
        try container.encodeIfPresent(isEnabled, forKey: .isEnabled)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(lastSeen, forKey: .lastSeen)
        try container.encodeIfPresent(ldap, forKey: .ldap)
        try container.encodeIfPresent(ldapDn, forKey: .ldapDn)
        try container.encodeIfPresent(passwordChangeRequired, forKey: .passwordChangeRequired)
        try container.encode(permissions, forKey: .permissions)
        try container.encode(shaperCeiling, forKey: .shaperCeiling)
        try container.encode(shaperRate, forKey: .shaperRate)
        try container.encodeIfPresent(totpEnabled, forKey: .totpEnabled)
        try container.encodeIfPresent(uid, forKey: .uid)
        try container.encodeIfPresent(unixUsername, forKey: .unixUsername)
        try container.encode(username, forKey: .username)
        try container.encode(groups, forKey: .groups)
    }
}

