//
// EnableTOTPRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct EnableTOTPRequest: Codable, Hashable {

    public var key: String
    public var otp: String

    public init(key: String, otp: String) {
        self.key = key
        self.otp = otp
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case otp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(otp, forKey: .otp)
    }



}
