//
// FilesystemPermissionPartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FilesystemPermissionPartialUpdate: Codable, JSONEncodable, Hashable {

    public var path: String?
    public var readOnly: Bool?
    public var user: Int?
    public var group: Int?

    public init(path: String? = nil, readOnly: Bool? = nil, user: Int? = nil, group: Int? = nil) {
        self.path = path
        self.readOnly = readOnly
        self.user = user
        self.group = group
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case readOnly = "read_only"
        case user
        case group
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(readOnly, forKey: .readOnly)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(group, forKey: .group)
    }
}

