//
// GenerateProxiesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateProxiesRequest: Codable, JSONEncodable, Hashable {

    public var bundles: [Int]?
    public var directories: [Int]?
    public var proxyProfiles: [Int]
    public var enqueueAtFront: Bool?
    public var force: Bool?

    public init(bundles: [Int]? = nil, directories: [Int]? = nil, proxyProfiles: [Int], enqueueAtFront: Bool? = nil, force: Bool? = nil) {
        self.bundles = bundles
        self.directories = directories
        self.proxyProfiles = proxyProfiles
        self.enqueueAtFront = enqueueAtFront
        self.force = force
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bundles
        case directories
        case proxyProfiles = "proxy_profiles"
        case enqueueAtFront = "enqueue_at_front"
        case force
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bundles, forKey: .bundles)
        try container.encodeIfPresent(directories, forKey: .directories)
        try container.encode(proxyProfiles, forKey: .proxyProfiles)
        try container.encodeIfPresent(enqueueAtFront, forKey: .enqueueAtFront)
        try container.encodeIfPresent(force, forKey: .force)
    }
}

