//
// ImportAIDatasetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImportAIDatasetRequest: Codable, JSONEncodable, Hashable {

    public var connection: Int
    public var path: String
    public var replace: Bool
    public var rename: String?

    public init(connection: Int, path: String, replace: Bool, rename: String? = nil) {
        self.connection = connection
        self.path = path
        self.replace = replace
        self.rename = rename
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connection
        case path
        case replace
        case rename
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(connection, forKey: .connection)
        try container.encode(path, forKey: .path)
        try container.encode(replace, forKey: .replace)
        try container.encodeIfPresent(rename, forKey: .rename)
    }
}

