//
// LDAPServerGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct LDAPServerGroup: Codable, Hashable {

    public var dn: String
    public var name: String
    public var users: [LDAPServerUser]

    public init(dn: String, name: String, users: [LDAPServerUser]) {
        self.dn = dn
        self.name = name
        self.users = users
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dn
        case name
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dn, forKey: .dn)
        try container.encode(name, forKey: .name)
        try container.encode(users, forKey: .users)
    }



}
