//
// LocateEndpointRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LocateEndpointRequest: Codable, JSONEncodable, Hashable {

    public var path: String?
    public var asset: Int?

    public init(path: String? = nil, asset: Int? = nil) {
        self.path = path
        self.asset = asset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case asset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(asset, forKey: .asset)
    }
}

