//
// LocateProxiesEndpointRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LocateProxiesEndpointRequest: Codable, JSONEncodable, Hashable {

    public var paths: [String]

    public init(paths: [String]) {
        self.paths = paths
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paths
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(paths, forKey: .paths)
    }
}

