//
// MediaFileTemplateUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaFileTemplateUpdate: Codable, JSONEncodable, Hashable {

    public var file: MediaFileReference
    public var name: String

    public init(file: MediaFileReference, name: String) {
        self.file = file
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case file
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(file, forKey: .file)
        try container.encode(name, forKey: .name)
    }
}

