//
// MediaFilePartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaFilePartialUpdate: Codable, Hashable {

    public var info: [String: String]?
    public var customFields: [String: String]?
    public var totalFiles: Int?
    public var needsRescan: Bool?
    public var bookmarkedBy: Set<Int>?

    public init(info: [String: String]? = nil, customFields: [String: String]? = nil, totalFiles: Int? = nil, needsRescan: Bool? = nil, bookmarkedBy: Set<Int>? = nil) {
        self.info = info
        self.customFields = customFields
        self.totalFiles = totalFiles
        self.needsRescan = needsRescan
        self.bookmarkedBy = bookmarkedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case info
        case customFields = "custom_fields"
        case totalFiles = "total_files"
        case needsRescan = "needs_rescan"
        case bookmarkedBy = "bookmarked_by"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(info, forKey: .info)
        try container.encodeIfPresent(customFields, forKey: .customFields)
        try container.encodeIfPresent(totalFiles, forKey: .totalFiles)
        try container.encodeIfPresent(needsRescan, forKey: .needsRescan)
        try container.encodeIfPresent(bookmarkedBy, forKey: .bookmarkedBy)
    }
}

