//
// MediaFileTemplatePartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MediaFileTemplatePartialUpdate: Codable, Hashable {

    public var file: MediaFileReference?
    public var name: String?

    public init(file: MediaFileReference? = nil, name: String? = nil) {
        self.file = file
        self.name = name
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case file
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(file, forKey: .file)
        try container.encodeIfPresent(name, forKey: .name)
    }



}
