//
// MediaFilesLookupRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaFilesLookupRequest: Codable, JSONEncodable, Hashable {

    public var query: String

    public init(query: String) {
        self.query = query
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(query, forKey: .query)
    }
}

