//
// MemberPreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MemberPreview: Codable, Hashable {

    public var id: Int
    public var avatar: String?
    public var email: String?

    public init(id: Int, avatar: String? = nil, email: String? = nil) {
        self.id = id
        self.avatar = avatar
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case avatar
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

