//
// NTPServerPartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct NTPServerPartialUpdate: Codable, Hashable {

    public var address: String?
    public var options: String?

    public init(address: String? = nil, options: String? = nil) {
        self.address = address
        self.options = options
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(options, forKey: .options)
    }



}
