//
// PathInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PathInput: Codable, Hashable {

    public var input: [String]

    public init(input: [String]) {
        self.input = input
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case input
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(input, forKey: .input)
    }
}

