//
// ProxyGenerator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProxyGenerator: Codable, Hashable {

    public var id: String
    public var name: String
    public var properties: ProxyGeneratorProperties

    public init(id: String, name: String, properties: ProxyGeneratorProperties) {
        self.id = id
        self.name = name
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(properties, forKey: .properties)
    }
}

