//
// RenderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderRequest: Codable, JSONEncodable, Hashable {

    public var destination: String

    public init(destination: String) {
        self.destination = destination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(destination, forKey: .destination)
    }
}

