//
// RestoreEndpointRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct RestoreEndpointRequest: Codable, Hashable {

    public var name: String
    public var source: [TapeJobSource]
    public var exclude: [String]
    public var tape: String
    public var export: Bool?
    public var startDate: Date

    public init(name: String, source: [TapeJobSource], exclude: [String], tape: String, export: Bool? = nil, startDate: Date) {
        self.name = name
        self.source = source
        self.exclude = exclude
        self.tape = tape
        self.export = export
        self.startDate = startDate
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case source
        case exclude
        case tape
        case export
        case startDate = "start_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(source, forKey: .source)
        try container.encode(exclude, forKey: .exclude)
        try container.encode(tape, forKey: .tape)
        try container.encodeIfPresent(export, forKey: .export)
        try container.encode(startDate, forKey: .startDate)
    }



}
