//
// SavedSearch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SavedSearch: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var user: ElementsUserMiniReference
    public var root: AnyOfMediaRootMiniReferenceAnyType?
    public var query: [String]
    public var url: String
    public var name: String
    public var shared: Bool?

    public init(id: Int, user: ElementsUserMiniReference, root: AnyOfMediaRootMiniReferenceAnyType? = nil, query: [String], url: String, name: String, shared: Bool? = nil) {
        self.id = id
        self.user = user
        self.root = root
        self.query = query
        self.url = url
        self.name = name
        self.shared = shared
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case root
        case query
        case url
        case name
        case shared
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(user, forKey: .user)
        try container.encodeIfPresent(root, forKey: .root)
        try container.encode(query, forKey: .query)
        try container.encode(url, forKey: .url)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(shared, forKey: .shared)
    }
}

