//
// ScannerDiscoverEndpointRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScannerDiscoverEndpointRequest: Codable, Hashable {

    public var path: String
    public var recursive: Bool?

    public init(path: String, recursive: Bool? = nil) {
        self.path = path
        self.recursive = recursive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case recursive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encodeIfPresent(recursive, forKey: .recursive)
    }
}

