//
// ScannerScanEndpointRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScannerScanEndpointRequest: Codable, Hashable {

    public var path: String
    public var recursive: Bool?
    public var notify: Bool?
    public var forceRescan: Bool?

    public init(path: String, recursive: Bool? = nil, notify: Bool? = nil, forceRescan: Bool? = nil) {
        self.path = path
        self.recursive = recursive
        self.notify = notify
        self.forceRescan = forceRescan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case recursive
        case notify
        case forceRescan = "force_rescan"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encodeIfPresent(recursive, forKey: .recursive)
        try container.encodeIfPresent(notify, forKey: .notify)
        try container.encodeIfPresent(forceRescan, forKey: .forceRescan)
    }
}

