//
// SlackConnectionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SlackConnectionStatus: Codable, Hashable {

    public var ok: Bool
    public var team: String
    public var user: String
    public var url: String

    public init(ok: Bool, team: String, user: String, url: String) {
        self.ok = ok
        self.team = team
        self.user = user
        self.url = url
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case team
        case user
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(team, forKey: .team)
        try container.encode(user, forKey: .user)
        try container.encode(url, forKey: .url)
    }



}
