//
// SnapshotUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SnapshotUpdate: Codable, JSONEncodable, Hashable {

    public var workspace: Int
    public var name: String?

    public init(workspace: Int, name: String? = nil) {
        self.workspace = workspace
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workspace
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workspace, forKey: .workspace)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

