//
// SubclipUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubclipUpdate: Codable, JSONEncodable, Hashable {

    public var asset: AssetMiniReference
    public var rendered: AnyOfAssetMiniReferenceAnyType?
    public var shared: Bool?
    public var name: String?
    public var tIn: Double
    public var tOut: Double
    public var root: MediaRootMiniReference

    public init(asset: AssetMiniReference, rendered: AnyOfAssetMiniReferenceAnyType? = nil, shared: Bool? = nil, name: String? = nil, tIn: Double, tOut: Double, root: MediaRootMiniReference) {
        self.asset = asset
        self.rendered = rendered
        self.shared = shared
        self.name = name
        self.tIn = tIn
        self.tOut = tOut
        self.root = root
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asset
        case rendered
        case shared
        case name
        case tIn = "t_in"
        case tOut = "t_out"
        case root
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(asset, forKey: .asset)
        try container.encodeIfPresent(rendered, forKey: .rendered)
        try container.encodeIfPresent(shared, forKey: .shared)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(tIn, forKey: .tIn)
        try container.encode(tOut, forKey: .tOut)
        try container.encode(root, forKey: .root)
    }
}

