//
// SubtitleClipboardEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubtitleClipboardEntry: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var subtitle: AssetMiniReference
    public var bundle: AnyOfMediaFileBundleMiniReferenceAnyType?
    public var date: Date

    public init(id: Int, subtitle: AssetMiniReference, bundle: AnyOfMediaFileBundleMiniReferenceAnyType? = nil, date: Date) {
        self.id = id
        self.subtitle = subtitle
        self.bundle = bundle
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case subtitle
        case bundle
        case date
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encodeIfPresent(bundle, forKey: .bundle)
        try container.encode(date, forKey: .date)
    }
}

