//
// TagMediaDirectoryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TagMediaDirectoryRequest: Codable, Hashable {

    public var tag: Int
    public var add: Bool

    public init(tag: Int, add: Bool) {
        self.tag = tag
        self.add = add
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tag
        case add
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tag, forKey: .tag)
        try container.encode(add, forKey: .add)
    }
}

