//
// TasksSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct TasksSummary: Codable, Hashable {

    public var running: [TaskInfo]
    public var pendingCount: Int

    public init(running: [TaskInfo], pendingCount: Int) {
        self.running = running
        self.pendingCount = pendingCount
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case running
        case pendingCount = "pending_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(running, forKey: .running)
        try container.encode(pendingCount, forKey: .pendingCount)
    }



}
