//
// TeamsMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TeamsMessage: Codable, Hashable {

    public var recipient: String
    public var text: String

    public init(recipient: String, text: String) {
        self.recipient = recipient
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipient
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipient, forKey: .recipient)
        try container.encode(text, forKey: .text)
    }
}

