//
// TestExternalTranscoderConnectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct TestExternalTranscoderConnectionRequest: Codable, Hashable {

    public var type: String
    public var address: String

    public init(type: String, address: String) {
        self.type = type
        self.address = address
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(address, forKey: .address)
    }



}
