//
// TimeEndpointRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct TimeEndpointRequest: Codable, Hashable {

    public var time: Double
    public var timezone: Timezone

    public init(time: Double, timezone: Timezone) {
        self.time = time
        self.timezone = timezone
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case timezone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(time, forKey: .time)
        try container.encode(timezone, forKey: .timezone)
    }



}
