//
// TimelineExportRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct TimelineExportRequest: Codable, Hashable {

    public var project: AnyCodable
    public var sequence: AnyCodable
    public var format: String

    public init(project: AnyCodable, sequence: AnyCodable, format: String) {
        self.project = project
        self.sequence = sequence
        self.format = format
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case project
        case sequence
        case format
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(project, forKey: .project)
        try container.encode(sequence, forKey: .sequence)
        try container.encode(format, forKey: .format)
    }



}
