//
// VeritoneJobList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VeritoneJobList: Codable, JSONEncodable, Hashable {

    public var jobs: [[String: String]]
    public var count: Int

    public init(jobs: [[String: String]], count: Int) {
        self.jobs = jobs
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobs
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobs, forKey: .jobs)
        try container.encode(count, forKey: .count)
    }
}

