//
// VeritoneUploadRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VeritoneUploadRequest: Codable, JSONEncodable, Hashable {

    public var root: Int
    public var file: Int?
    public var bundle: Int?

    public init(root: Int, file: Int? = nil, bundle: Int? = nil) {
        self.root = root
        self.file = file
        self.bundle = bundle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case root
        case file
        case bundle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(root, forKey: .root)
        try container.encodeIfPresent(file, forKey: .file)
        try container.encodeIfPresent(bundle, forKey: .bundle)
    }
}

