//
// VolumeMiniReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VolumeMiniReference: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case generic = "generic"
        case genericMount = "generic-mount"
        case snfs = "snfs"
        case btrfs = "btrfs"
        case s3fs = "s3fs"
        case lizardfs = "lizardfs"
        case bcachefs = "bcachefs"
        case isilon = "isilon"
        case beegfs = "beegfs"
    }
    public var id: Int?
    public var name: String?
    public var path: String?
    public var displayName: String?
    public var visualTag: String?
    public var type: ModelType?

    public init(id: Int? = nil, name: String? = nil, path: String? = nil, displayName: String? = nil, visualTag: String? = nil, type: ModelType? = nil) {
        self.id = id
        self.name = name
        self.path = path
        self.displayName = displayName
        self.visualTag = visualTag
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case path
        case displayName = "display_name"
        case visualTag = "visual_tag"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(visualTag, forKey: .visualTag)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

