//
// VolumeStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VolumeStats: Codable, JSONEncodable, Hashable {

    public var usage: [VolumeStat]

    public init(usage: [VolumeStat]) {
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case usage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(usage, forKey: .usage)
    }
}

