//
// WorkspaceMoveToRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkspaceMoveToRequest: Codable, Hashable {

    public var production: Int

    public init(production: Int) {
        self.production = production
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case production
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(production, forKey: .production)
    }
}

