//
// ClickAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import PromiseKit

open class ClickAPI {
    /**

     - parameter uploadId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func abortClickUpload( uploadId: String, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        abortClickUploadWithRequestBuilder(uploadId: uploadId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - DELETE /api/2/click/uploads/{upload_id}
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter uploadId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func abortClickUploadWithRequestBuilder(uploadId: String) -> RequestBuilder<Void> {
        var path = "/api/2/click/uploads/{upload_id}"
        let uploadIdPreEscape = "\(APIHelper.mapValueToPathItem(uploadId))"
        let uploadIdPostEscape = uploadIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{upload_id}", with: uploadIdPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = ElementsSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter uploadId: (path)  
     - parameter clickBackgroundUploadEndpointRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func continueClickUploadInBackground( uploadId: String,  clickBackgroundUploadEndpointRequest: ClickBackgroundUploadEndpointRequest, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        continueClickUploadInBackgroundWithRequestBuilder(uploadId: uploadId, clickBackgroundUploadEndpointRequest: clickBackgroundUploadEndpointRequest).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /api/2/click/uploads/{upload_id}/background
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter uploadId: (path)  
     - parameter clickBackgroundUploadEndpointRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func continueClickUploadInBackgroundWithRequestBuilder(uploadId: String, clickBackgroundUploadEndpointRequest: ClickBackgroundUploadEndpointRequest) -> RequestBuilder<Void> {
        var path = "/api/2/click/uploads/{upload_id}/background"
        let uploadIdPreEscape = "\(APIHelper.mapValueToPathItem(uploadId))"
        let uploadIdPostEscape = uploadIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{upload_id}", with: uploadIdPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clickBackgroundUploadEndpointRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = ElementsSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter clickGallery: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<ClickGallery>
     */
    open class func createClickGallery( connectionId: String,  clickGallery: ClickGallery, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<ClickGallery> {
        let deferred = Promise<ClickGallery>.pending()
        createClickGalleryWithRequestBuilder(connectionId: connectionId, clickGallery: clickGallery).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /api/2/click/connections/{connection_id}/galleries
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter clickGallery: (body)  
     - returns: RequestBuilder<ClickGallery> 
     */
    open class func createClickGalleryWithRequestBuilder(connectionId: String, clickGallery: ClickGallery) -> RequestBuilder<ClickGallery> {
        var path = "/api/2/click/connections/{connection_id}/galleries"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clickGallery)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ClickGallery>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter clickGalleryLink: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<ClickGalleryLink>
     */
    open class func createClickGalleryLink( connectionId: String,  clickGalleryLink: ClickGalleryLink, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<ClickGalleryLink> {
        let deferred = Promise<ClickGalleryLink>.pending()
        createClickGalleryLinkWithRequestBuilder(connectionId: connectionId, clickGalleryLink: clickGalleryLink).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /api/2/click/connections/{connection_id}/gallery-links
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter clickGalleryLink: (body)  
     - returns: RequestBuilder<ClickGalleryLink> 
     */
    open class func createClickGalleryLinkWithRequestBuilder(connectionId: String, clickGalleryLink: ClickGalleryLink) -> RequestBuilder<ClickGalleryLink> {
        var path = "/api/2/click/connections/{connection_id}/gallery-links"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clickGalleryLink)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ClickGalleryLink>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func deleteClickGalleryLink( connectionId: String,  id: String, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        deleteClickGalleryLinkWithRequestBuilder(connectionId: connectionId, id: id).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - DELETE /api/2/click/connections/{connection_id}/gallery-links/{id}
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteClickGalleryLinkWithRequestBuilder(connectionId: String, id: String) -> RequestBuilder<Void> {
        var path = "/api/2/click/connections/{connection_id}/gallery-links/{id}"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = ElementsSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter limit: (query) Number of results to return per page. (optional)
     - parameter offset: (query) The initial index from which to return the results. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<InlineResponse200>
     */
    open class func getAllClickGalleries( connectionId: String,  ordering: String? = nil,  limit: Int? = nil,  offset: Int? = nil, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<InlineResponse200> {
        let deferred = Promise<InlineResponse200>.pending()
        getAllClickGalleriesWithRequestBuilder(connectionId: connectionId, ordering: ordering, limit: limit, offset: offset).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /api/2/click/connections/{connection_id}/galleries
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter limit: (query) Number of results to return per page. (optional)
     - parameter offset: (query) The initial index from which to return the results. (optional)
     - returns: RequestBuilder<InlineResponse200> 
     */
    open class func getAllClickGalleriesWithRequestBuilder(connectionId: String, ordering: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<InlineResponse200> {
        var path = "/api/2/click/connections/{connection_id}/galleries"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "ordering": ordering?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<InlineResponse200>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter limit: (query) Number of results to return per page. (optional)
     - parameter offset: (query) The initial index from which to return the results. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<InlineResponse2001>
     */
    open class func getAllClickGalleryLinks( connectionId: String,  ordering: String? = nil,  limit: Int? = nil,  offset: Int? = nil, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<InlineResponse2001> {
        let deferred = Promise<InlineResponse2001>.pending()
        getAllClickGalleryLinksWithRequestBuilder(connectionId: connectionId, ordering: ordering, limit: limit, offset: offset).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /api/2/click/connections/{connection_id}/gallery-links
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter limit: (query) Number of results to return per page. (optional)
     - parameter offset: (query) The initial index from which to return the results. (optional)
     - returns: RequestBuilder<InlineResponse2001> 
     */
    open class func getAllClickGalleryLinksWithRequestBuilder(connectionId: String, ordering: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<InlineResponse2001> {
        var path = "/api/2/click/connections/{connection_id}/gallery-links"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "ordering": ordering?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<InlineResponse2001>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<ClickGallery>
     */
    open class func getClickGallery( connectionId: String,  id: String, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<ClickGallery> {
        let deferred = Promise<ClickGallery>.pending()
        getClickGalleryWithRequestBuilder(connectionId: connectionId, id: id).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /api/2/click/connections/{connection_id}/galleries/{id}
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<ClickGallery> 
     */
    open class func getClickGalleryWithRequestBuilder(connectionId: String, id: String) -> RequestBuilder<ClickGallery> {
        var path = "/api/2/click/connections/{connection_id}/galleries/{id}"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ClickGallery>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<ClickGalleryLink>
     */
    open class func getClickGalleryLink( connectionId: String,  id: String, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<ClickGalleryLink> {
        let deferred = Promise<ClickGalleryLink>.pending()
        getClickGalleryLinkWithRequestBuilder(connectionId: connectionId, id: id).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /api/2/click/connections/{connection_id}/gallery-links/{id}
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<ClickGalleryLink> 
     */
    open class func getClickGalleryLinkWithRequestBuilder(connectionId: String, id: String) -> RequestBuilder<ClickGalleryLink> {
        var path = "/api/2/click/connections/{connection_id}/gallery-links/{id}"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ClickGalleryLink>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter id: (path)  
     - parameter clickGallery: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<ClickGallery>
     */
    open class func patchClickGallery( connectionId: String,  id: String,  clickGallery: ClickGallery, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<ClickGallery> {
        let deferred = Promise<ClickGallery>.pending()
        patchClickGalleryWithRequestBuilder(connectionId: connectionId, id: id, clickGallery: clickGallery).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - PATCH /api/2/click/connections/{connection_id}/galleries/{id}
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter id: (path)  
     - parameter clickGallery: (body)  
     - returns: RequestBuilder<ClickGallery> 
     */
    open class func patchClickGalleryWithRequestBuilder(connectionId: String, id: String, clickGallery: ClickGallery) -> RequestBuilder<ClickGallery> {
        var path = "/api/2/click/connections/{connection_id}/galleries/{id}"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clickGallery)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ClickGallery>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter linkId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func sendClickGalleryLinkEmail( connectionId: String,  linkId: String, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        sendClickGalleryLinkEmailWithRequestBuilder(connectionId: connectionId, linkId: linkId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /api/2/click/connections/{connection_id}/gallery-links/{link_id}/send
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter linkId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func sendClickGalleryLinkEmailWithRequestBuilder(connectionId: String, linkId: String) -> RequestBuilder<Void> {
        var path = "/api/2/click/connections/{connection_id}/gallery-links/{link_id}/send"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let linkIdPreEscape = "\(APIHelper.mapValueToPathItem(linkId))"
        let linkIdPostEscape = linkIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{link_id}", with: linkIdPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = ElementsSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter clickStartUploadEndpointRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<TaskInfo>
     */
    open class func startClickUpload( clickStartUploadEndpointRequest: ClickStartUploadEndpointRequest, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<TaskInfo> {
        let deferred = Promise<TaskInfo>.pending()
        startClickUploadWithRequestBuilder(clickStartUploadEndpointRequest: clickStartUploadEndpointRequest).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /api/2/click/uploads
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter clickStartUploadEndpointRequest: (body)  
     - returns: RequestBuilder<TaskInfo> 
     */
    open class func startClickUploadWithRequestBuilder(clickStartUploadEndpointRequest: ClickStartUploadEndpointRequest) -> RequestBuilder<TaskInfo> {
        let path = "/api/2/click/uploads"
        let URLString = ElementsSDKAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clickStartUploadEndpointRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<TaskInfo>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter connectionId: (path)  
     - parameter id: (path)  
     - parameter addAssetsToClickGallery: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<AddAssetsToClickGallery>
     */
    open class func updateClickGallery( connectionId: String,  id: String,  addAssetsToClickGallery: AddAssetsToClickGallery, apiResponseQueue: DispatchQueue = ElementsSDKAPI.apiResponseQueue) -> Promise<AddAssetsToClickGallery> {
        let deferred = Promise<AddAssetsToClickGallery>.pending()
        updateClickGalleryWithRequestBuilder(connectionId: connectionId, id: id, addAssetsToClickGallery: addAssetsToClickGallery).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - PUT /api/2/click/connections/{connection_id}/galleries/{id}
     - ### Required permissions    * User account permission: `cloud:access` 
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter connectionId: (path)  
     - parameter id: (path)  
     - parameter addAssetsToClickGallery: (body)  
     - returns: RequestBuilder<AddAssetsToClickGallery> 
     */
    open class func updateClickGalleryWithRequestBuilder(connectionId: String, id: String, addAssetsToClickGallery: AddAssetsToClickGallery) -> RequestBuilder<AddAssetsToClickGallery> {
        var path = "/api/2/click/connections/{connection_id}/galleries/{id}"
        let connectionIdPreEscape = "\(APIHelper.mapValueToPathItem(connectionId))"
        let connectionIdPostEscape = connectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{connection_id}", with: connectionIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let URLString = ElementsSDKAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addAssetsToClickGallery)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<AddAssetsToClickGallery>.Type = ElementsSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
